name: copilot
description: "Track your expenses"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  flex_color_scheme: 7.3.1
  flutter_bloc: ^8.1.6
  pie_chart: ^5.4.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  shimmer: ^3.0.0
  logger: ^2.0.2
  intl: ^0.19.0
  flutter_iconpicker: ^3.4.6
  flutter_material_color_picker: ^1.2.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/e-wallet1000.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#d1afce"
  adaptive_icon_foreground: "assets/e-wallet_foreground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
